apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret-al-25-03-2026
  namespace: preprod-al-25-03-2026
type: Opaque
stringData:
  STRIPE_PUBLISHABLE_KEY: "pk_test_51TEoFLPnoI8fWa44Ftug4QzwJrRj18FUsdGBc2nIFAiGZh1Hxgwna7sMdWdjeZuZwtLNExrN1buYGwqJyA0Yck3M00gNrXI3q7"
  STRIPE_SECRET_KEY: "sk_test_51TEoFLPnoI8fWa44WBV66bAnHvUS2w99BayfmqhwmqoxQyswXiy32ozYQBo33NvOICqlpaC1pFIN6HI48AjxnFZy003bP1AE5s"